apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeployMV
  labels:
    app: autodeployMV
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1717150755224
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeployMV
  template:
    metadata:
      labels:
        app: autodeployMV
    spec:
      containers:
        - name: autodeployMV
          image: acrworkflow1717150755224.azurecr.io/image-workflow-1717150755224:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
