apiVersion: v1
kind: Service
metadata:
  name: autodeployMV
  namespace: namespace-workflow-1717150755224
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeployMV
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000